# Generated by Django 4.2.7 on 2023-11-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('uf', models.CharField(max_length=10)),
                ('utm', models.CharField(max_length=10)),
                ('dolar_obs', models.CharField(max_length=10)),
                ('euro', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Data',
                'verbose_name_plural': 'Data',
                'ordering': ['-date'],
            },
        ),
    ]
