# Generated by Django 4.2.7 on 2023-11-20 16:21

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('comerceapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='data',
            managers=[
                ('data', django.db.models.manager.Manager()),
            ],
        ),
    ]
