# Generated by Django 4.2.7 on 2023-11-20 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comerceapp', '0002_alter_data_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='data',
            managers=[
            ],
        ),
    ]
