# Generated by Django 4.2.7 on 2023-11-20 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comerceapp', '0004_alter_data_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name': 'Data', 'verbose_name_plural': 'Data'},
        ),
    ]
