# Generated by Django 4.2.7 on 2023-11-20 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comerceapp', '0005_alter_data_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name': 'Data', 'verbose_name_plural': 'Datas'},
        ),
        migrations.RemoveField(
            model_name='data',
            name='date',
        ),
    ]
