# Generated by Django 4.2.7 on 2023-11-20 21:37

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('comerceapp', '0006_alter_data_options_remove_data_date'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='data',
            managers=[
                ('data', django.db.models.manager.Manager()),
            ],
        ),
    ]
