# Generated by Django 4.2.7 on 2023-11-20 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comerceapp', '0008_data_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='dolar_obs',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='data',
            name='euro',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='data',
            name='uf',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='data',
            name='utm',
            field=models.CharField(max_length=50),
        ),
    ]
