# Generated by Django 4.2.6 on 2023-12-09 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comerceapp', '0012_alter_data_options_remove_data_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'ordering': ['day'], 'verbose_name': 'Data', 'verbose_name_plural': 'Datas'},
        ),
        migrations.AlterField(
            model_name='data',
            name='day',
            field=models.IntegerField(default=''),
        ),
    ]
